runtime: python
env: flex
entrypoint: gunicorn --bind :$PORT --workers 2 --worker-class uvicorn.workers.UvicornWorker  --threads 8 app.main:app
runtime_config:
  python_version: 3

skip_files:
  - frontend_vue2
  - Pipfile.*
  - vetur\.config\.js

manual_scaling:
  instances: 1

env_variables:
  GOOGLE_API_KEY: "asdfasdfasdfasdfasdf"
  TANKERKOENIG_API_KEY: "asdfasdfasdfasdfasdf"

