runtime: python39
env: standard
instance_class: F1
handlers:
  - url: .*
    script: auto
entrypoint: gunicorn --bind :$PORT --workers 1 --worker-class uvicorn.workers.UvicornWorker  --threads 2 app.main:app
env_variables:
  GOOGLE_API_KEY: asdfasdfasdf
  TANKERKOENIG_API_KEY: asdfasdfasdf
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_instances: 1
network: {}